<a href="https://colab.research.google.com/github/wojr21/courses/blob/main/DS_bootcamp_exercises/051_060_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 51](#1)
* [Ćwiczenie 52](#2)
* [Ćwiczenie 53](#3)
* [Ćwiczenie 54](#4)
* [Ćwiczenie 55](#5)
* [Ćwiczenie 56](#6)
* [Ćwiczenie 57](#7)
* [Ćwiczenie 58](#8)
* [Ćwiczenie 59](#9)
* [Ćwiczenie 60](#10)

### <a name='0'></a>Import biblioteki

In [60]:
import numpy as np

np.random.seed(42)
np.__version__

'1.18.5'

### <a name='1'></a> Ćwiczenie 51
Podane są poniżej dwie tablice $A$ i $B$:


```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.





In [3]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])

np.concatenate([A, B], axis = 0)

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

* Połącz te tablice w następujący sposób:


```
array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.concatenate()_.

In [4]:
np.concatenate([A, B], axis = 1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Ćwiczenie 52
Podana jest tablica zawierająca dane _data_ oraz tablica zawierająca docelową klasę dla danego wiersza _target_:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
```



Połącz te tablice w jedną tak jak pokazano poniżej:


```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```



In [5]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

np.concatenate([data, target], axis = 1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Ćwiczenie 53
Podane są trzy poniższe jednowymiarowe tablice:  


```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Przekształć każdą z tych tablic w kolumnę i sklej w jedną dużą tablicę.

__Oczekiwany wynik:__


```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

__Wskazówka:__ Wykorzystaj funkcję _np.column_stack()_.



In [72]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

np.column_stack((feature1, feature2, feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Ćwiczenie 54
Podana jest poniższa dwuwymiarowa tablica:

```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```

Podziel tablicę na 3 części tak aby pierwsze dwie kolumny stanowiły pierwszą tablicę $A1$, cztery kolejne drugą tablicę $A2$ oraz dwie ostatnie trzecią tablicę $A3$.

__Wskazówka:__ Wykorzystaj funkcję _np.split()_.

In [53]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1

A1, A2, A3 = np.split(A, [2, 6], axis = 1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Ćwiczenie 55
Podana jest poniższa tablica $A$:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```
Wyznacz łączną liczbę elementów niezerowych dla tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.


In [54]:
A = np.random.randint(low=0, high=2, size=(10, 6))

np.count_nonzero(A)

38

Wyznacz łączną liczbę elementów niezerowych dla każdego wiersza tej tablicy.

__Wskazówka:__ Wykorzystaj funkcję _np.count_nonzero()_.

In [55]:
np.count_nonzero(A, axis = 1)

array([4, 2, 1, 5, 4, 3, 3, 6, 4, 6])

### <a name='6'></a> Ćwiczenie 56
Poniżej podana jest przykładowa tablica $A$:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```


Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować tablice z określoną precyzją. Ustaw jej wartość na 4 i wydrukuj tablicę $A$.



In [68]:
A = np.random.randn(10, 4)

np.set_printoptions(precision = 4)
A

array([[ 0.4967, -0.1383,  0.6477,  1.523 ],
       [-0.2342, -0.2341,  1.5792,  0.7674],
       [-0.4695,  0.5426, -0.4634, -0.4657],
       [ 0.242 , -1.9133, -1.7249, -0.5623],
       [-1.0128,  0.3142, -0.908 , -1.4123],
       [ 1.4656, -0.2258,  0.0675, -1.4247],
       [-0.5444,  0.1109, -1.151 ,  0.3757],
       [-0.6006, -0.2917, -0.6017,  1.8523],
       [-0.0135, -1.0577,  0.8225, -1.2208],
       [ 0.2089, -1.9597, -1.3282,  0.1969]])

### <a name='7'></a> Ćwiczenie 57
Podana jest poniższa tablica numpy $A$:

```
A = np.array([1.2e-6, 1.7e-7])
```

Ustaw wartość precyzji na 8. Następnie ustaw odopowiednią opcję biblioteki numpy pozwalającą stłumić notację wykładniczą. Wydrukuj tablicę $A$.

__Oczekiwany wynik:__


```
array([0.0000012 , 0.00000017])
```





In [43]:
A = np.array([1.2e-6, 1.7e-7])

np.set_printoptions(precision = 8, suppress = True)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Ćwiczenie 58
Podana jest poniższa tablica numpy $A$:

```
A = np.random.randn(8, 4)
```
Usuń trzecią kolumnę z tablicy $A$.

__Oczekiwany wynik:__


```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```
__Wskazówka:__ Wykorzystaj funkcję _np.delete()_.




In [73]:
A = np.random.randn(8, 4)
np.delete(A, 2, axis = 1)

array([[-0.6939,  0.455 ,  0.7608],
       [ 1.6644,  1.5619, -2.0979],
       [-0.6785,  0.0757,  1.9679],
       [ 0.0188,  0.6537, -0.3466],
       [-1.9248, -0.0786, -1.2445],
       [-1.8149,  1.9364,  0.1874],
       [ 1.3627, -0.8315,  0.9552],
       [ 2.1104, -1.1685,  0.3818]])

### <a name='9'></a> Ćwiczenie 59
Podana jest tablica jednowymiarowa $v$ (wektor):

```
v = np.array([3, 4, -2])
```
Policz normę wektora $v$.


In [70]:
v = np.array([3, 4, -2])

np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Ćwiczenie 60
Poniżej podana jest przykładowa tablica $A$:


```
A = np.random.randint(10, size=(100, 30))
```
Ustaw odopowiednią opcję biblioteki numpy pozwalającą drukować 10 skrajnych elementów. Wydrukuj tablicę $A$.


In [71]:
A = np.random.randint(10, size=(100, 30))

np.set_printoptions(edgeitems = 10)
A

array([[6, 8, 9, 9, 2, 6, 0, 3, 3, 4, ..., 5, 3, 9, 6, 8, 6, 0, 0, 8, 8],
       [3, 8, 2, 6, 5, 7, 8, 4, 0, 2, ..., 6, 1, 2, 0, 4, 0, 7, 0, 0, 1],
       [1, 5, 6, 4, 0, 0, 2, 1, 4, 9, ..., 1, 5, 5, 0, 8, 5, 2, 3, 3, 2],
       [9, 2, 2, 3, 6, 3, 8, 0, 7, 6, ..., 9, 8, 3, 0, 1, 0, 4, 4, 6, 8],
       [8, 2, 2, 2, 3, 7, 5, 7, 0, 7, ..., 8, 1, 1, 1, 5, 2, 8, 3, 0, 3],
       [0, 4, 3, 7, 7, 6, 2, 0, 0, 2, ..., 0, 0, 4, 2, 3, 2, 0, 0, 4, 5],
       [2, 8, 4, 7, 0, 4, 2, 0, 3, 4, ..., 7, 1, 5, 6, 1, 9, 1, 9, 0, 7],
       [0, 8, 5, 6, 9, 6, 9, 2, 1, 8, ..., 1, 1, 6, 5, 2, 8, 9, 5, 9, 9],
       [5, 0, 3, 9, 5, 5, 4, 0, 7, 4, ..., 9, 2, 0, 7, 2, 9, 6, 9, 4, 9],
       [4, 6, 8, 4, 0, 9, 9, 0, 1, 5, ..., 2, 4, 5, 8, 4, 0, 3, 4, 9, 9],
       ...,
       [8, 0, 7, 3, 8, 4, 2, 8, 8, 3, ..., 1, 4, 4, 4, 3, 4, 2, 0, 4, 8],
       [8, 3, 2, 0, 1, 7, 0, 7, 6, 7, ..., 3, 8, 2, 3, 6, 6, 3, 5, 2, 5],
       [1, 7, 1, 6, 8, 0, 7, 6, 5, 5, ..., 8, 0, 2, 7, 2, 3, 7, 0, 5, 0],
       [0, 7, 3, 0, 9, 6, 