<a href="https://colab.research.google.com/github/wojr21/courses/blob/main/data_science_bootcamp/12_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.3.0'

### Wprowadzenie - pierwszy model

Model sekwencyjny to nic innego jak liniowy stos warstw

In [3]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Abu dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy Dense. Aby dodać warstwię do modelu należy użyć metody .add()

In [4]:
from tensorflow.keras.layers import Dense

model.add(Dense(units = 4, input_shape = (10,)))

Wyświetlenie podsummowania modelu: metoda .summary

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy

In [6]:
model.add(Dense(units = 2))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


### Funkcje aktywacji

Istotnym elementem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x) = x$.

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji, aby rozwiązywać problemy nieliniowe.

In [7]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start = -3, stop = 3, num = 300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [8]:
px.line(data, x = 'data', y = 'linear', width = 500, height = 400,
        range_y = [-3, 3])

In [9]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [11]:
px.line(data, x = 'data', y = 'sigmoid', width = 500, height = 400,
        range_y = [-0.5, 1.5])

In [12]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [13]:
px.line(data, x = 'data', y = 'relu', width = 500, height = 400,
        range_y = [-0.5, 1.5])

In [15]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [17]:
px.line(data, x = 'data', y = 'tanh', width = 500, height = 400,
        range_y = [-1.5, 1.5])

In [19]:
model = Sequential()
model.add(Dense(units = 8, activation = 'relu', input_shape = (10,)))
model.add(Dense(units = 1, activation = 'sigmoid'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


### Kompilacja modelu

Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:


*   rodzaj optymalizatora
*   funkcję straty
*   metryki, które będziemy obserwować podczas trenowania sieci


Przykłady:

In [ ]:
# klasyfikacja binarna
model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

# regresja
model.compile(optimizer = 'rmsprop',
              loss = 'mse')

### Trenowanie modelu

Za dane wejściowe do modelu należy przekazać NumPy arrays:
*   **epochs** - krotność przejścia danych przez sieć w procesie uczenia, iteracje
*   **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
*   **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
*   **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [20]:
# model.fit(data, labels, epochs = 10, batch_size = 32)
# model.fit(data, labels, epochs = 10, batch_size = 32, validation_split = 0.2)
# model.fit(data, labels, epochs = 10, batch_size = 32, validation_split = 0.2, validation_data = (x_val, y_val))

### Przykład - klasyfikacja binarna

In [21]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [22]:
data[:3]

array([[ 4.11010220e-01, -1.01924079e+00,  1.41766146e+00,
        -8.99136017e-01,  7.69012074e-01, -6.66760581e-01,
         2.15986412e-01, -5.92307855e-01,  4.10559649e-01,
        -6.54054786e-01, -5.33918374e-01, -5.66770355e-01,
         4.56556493e-01, -5.75977170e-01, -7.31614152e-01,
        -2.10338408e-01,  3.33701878e-01,  2.62862383e-01,
        -1.13004937e+00, -5.53661226e-01, -3.94180286e-01,
        -4.45980738e-01, -5.20007164e-01, -5.66828779e-01,
        -1.19463364e+00, -2.47745060e+00,  2.86305448e-01,
         7.93991762e-01, -4.65465162e-01,  6.21902499e-01,
         1.27533116e-01,  1.44400011e+00,  2.55853315e-01,
         1.39380428e+00,  2.87880237e-01, -5.24666090e-01,
         1.07900701e+00, -1.00744907e+00, -8.09155775e-01,
        -8.67633453e-01, -1.55752214e-01, -4.35995517e-01,
        -1.24672423e+00, -5.67410965e-01, -3.28516121e-01,
        -2.32569604e-01, -5.83949227e-02, -2.45575189e-01,
        -3.33802796e-01, -1.20023971e+00, -1.87236745e-0

In [23]:
labels[:10]

array([[1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0]])

In [24]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20, batch_size = 1)

Epoch 1/20
10000/10000 [==============================] - 9s 858us/step - loss: 0.7441 - accuracy: 0.5055
Epoch 2/20
10000/10000 [==============================] - 9s 859us/step - loss: 0.6899 - accuracy: 0.5627
Epoch 3/20
10000/10000 [==============================] - 9s 859us/step - loss: 0.6705 - accuracy: 0.6030
Epoch 4/20
10000/10000 [==============================] - 9s 863us/step - loss: 0.6439 - accuracy: 0.6419
Epoch 5/20
10000/10000 [==============================] - 9s 870us/step - loss: 0.6204 - accuracy: 0.6749
Epoch 6/20
10000/10000 [==============================] - 9s 871us/step - loss: 0.5944 - accuracy: 0.7092
Epoch 7/20
10000/10000 [==============================] - 9s 880us/step - loss: 0.5790 - accuracy: 0.7248
Epoch 8/20
10000/10000 [==============================] - 10s 978us/step - loss: 0.5705 - accuracy: 0.7424
Epoch 9/20
10000/10000 [==============================] - 9s 914us/step - loss: 0.5569 - accuracy: 0.7602
Epoch 10/20
10000/10000 [====================

In [25]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20, batch_size = 32)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.7379 - accuracy: 0.5010
Epoch 2/20
313/313 [==============================] - 0s 987us/step - loss: 0.6910 - accuracy: 0.5565
Epoch 3/20
313/313 [==============================] - 0s 992us/step - loss: 0.6727 - accuracy: 0.5831
Epoch 4/20
313/313 [==============================] - 0s 971us/step - loss: 0.6591 - accuracy: 0.6041
Epoch 5/20
313/313 [==============================] - 0s 997us/step - loss: 0.6451 - accuracy: 0.6314
Epoch 6/20
313/313 [==============================] - 0s 990us/step - loss: 0.6316 - accuracy: 0.6463
Epoch 7/20
313/313 [==============================] - 0s 991us/step - loss: 0.6166 - accuracy: 0.6711
Epoch 8/20
313/313 [==============================] - 0s 950us/step - loss: 0.6021 - accuracy: 0.6877
Epoch 9/20
313/313 [==============================] - 0s 997us/step - loss: 0.5878 - accuracy: 0.7013
Epoch 10/20
313/313 [==============================] - 0s 960us/step - loss: 0.5731 

In [26]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 20, batch_size = 32, validation_split = 0.2)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7484 - accuracy: 0.5141 - val_loss: 0.7261 - val_accuracy: 0.5025
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6950 - accuracy: 0.5491 - val_loss: 0.7219 - val_accuracy: 0.5065
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6744 - accuracy: 0.5756 - val_loss: 0.7224 - val_accuracy: 0.5015
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6585 - accuracy: 0.6005 - val_loss: 0.7237 - val_accuracy: 0.5050
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6437 - accuracy: 0.6295 - val_loss: 0.7270 - val_accuracy: 0.5025
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6283 - accuracy: 0.6518 - val_loss: 0.7330 - val_accuracy: 0.5085
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6130 - accuracy: 0.6693 - val_loss: 0.7450 - val_accuracy: 0.5020
Epoch 

In [28]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

history = model.fit(data, labels, epochs = 20, batch_size = 32,
                    validation_split = 0.2, verbose = 0)

In [29]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [30]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'rmsprop',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

history = model.fit(data, labels, epochs = 20, batch_size = 32, validation_split = 0.2,
          verbose = 1)

Epoch 1/20
250/250 [==============================] - 0s 2ms/step - loss: 0.7648 - accuracy: 0.4859 - val_loss: 0.7136 - val_accuracy: 0.5190
Epoch 2/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6956 - accuracy: 0.5439 - val_loss: 0.7143 - val_accuracy: 0.5070
Epoch 3/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6748 - accuracy: 0.5828 - val_loss: 0.7130 - val_accuracy: 0.5095
Epoch 4/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6582 - accuracy: 0.6044 - val_loss: 0.7175 - val_accuracy: 0.5035
Epoch 5/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6429 - accuracy: 0.6320 - val_loss: 0.7194 - val_accuracy: 0.5070
Epoch 6/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6274 - accuracy: 0.6544 - val_loss: 0.7247 - val_accuracy: 0.5115
Epoch 7/20
250/250 [==============================] - 0s 1ms/step - loss: 0.6121 - accuracy: 0.6760 - val_loss: 0.7316 - val_accuracy: 0.5175
Epoch 

In [31]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size = (5, 1))

In [32]:
model.predict(test_data)

array([[0.8606637 ],
       [0.826064  ],
       [0.33980197],
       [0.5212686 ],
       [0.6220614 ]], dtype=float32)

In [33]:
model.predict_proba(test_data)

Instructions for updating:
Please use `model.predict()` instead.


array([[0.8606637 ],
       [0.826064  ],
       [0.33980197],
       [0.5212686 ],
       [0.6220614 ]], dtype=float32)

In [34]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([[1],
       [1],
       [0],
       [1],
       [1]], dtype=int32)

### Przykład - klasyfikacja wieloklasowa

In [36]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [37]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [39]:
labels[:10]

array([[2],
       [3],
       [8],
       [5],
       [8],
       [0],
       [1],
       [2],
       [8],
       [6]])

In [40]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes = 10)
labels

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [41]:
labels[1]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [42]:
model = Sequential()
model.add(Dense(units = 32, activation = 'relu', input_shape = (150, )))
model.add(Dense(10, activation = 'softmax'))

model.compile(optimizer = 'rmsprop',
              loss = 'categorical_crossentropy',
              metrics = ['accuracy'])

model.fit(data, labels, epochs = 30, batch_size = 32, validation_split = 0.2)

Epoch 1/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3221 - accuracy: 0.1006 - val_loss: 2.3047 - val_accuracy: 0.1035
Epoch 2/30
250/250 [==============================] - 0s 1ms/step - loss: 2.3034 - accuracy: 0.1016 - val_loss: 2.3055 - val_accuracy: 0.0930
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 2.3019 - accuracy: 0.1050 - val_loss: 2.3062 - val_accuracy: 0.0875
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 2.3012 - accuracy: 0.1061 - val_loss: 2.3044 - val_accuracy: 0.0935
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2987 - accuracy: 0.1093 - val_loss: 2.3066 - val_accuracy: 0.0945
Epoch 6/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2953 - accuracy: 0.1110 - val_loss: 2.3079 - val_accuracy: 0.0950
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 2.2921 - accuracy: 0.1210 - val_loss: 2.3101 - val_accuracy: 0.0920
Epoch 

In [43]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[0.05094811, 0.08281544, 0.12501113, 0.12623623, 0.05612403,
        0.10241552, 0.05780708, 0.07208779, 0.21425122, 0.11230346],
       [0.12443727, 0.07349547, 0.05793479, 0.16305931, 0.07560699,
        0.14125405, 0.08840764, 0.09091493, 0.1431309 , 0.04175873],
       [0.01733026, 0.03945948, 0.06147062, 0.11242999, 0.16047047,
        0.20453246, 0.21087122, 0.1345702 , 0.02069299, 0.03817243],
       [0.0962842 , 0.05136006, 0.07322441, 0.14063534, 0.09206174,
        0.15175281, 0.08215698, 0.0654133 , 0.16214545, 0.08496571],
       [0.23108914, 0.09444888, 0.11823645, 0.04386828, 0.07735018,
        0.14213216, 0.05923793, 0.04579207, 0.0739276 , 0.11391725],
       [0.07202797, 0.10713156, 0.1543857 , 0.06911108, 0.1401567 ,
        0.07434324, 0.14945757, 0.10412029, 0.06447282, 0.0647931 ],
       [0.08360514, 0.06717191, 0.0793714 , 0.08774506, 0.12377689,
        0.09919007, 0.08942875, 0.12445028, 0.14951247, 0.09574808],
       [0.09263818, 0.09925242, 0.1121525

In [44]:
model.predict_classes(test_data)

array([8, 3, 6, 8, 0, 2, 8, 7, 3, 7])

### Przykład - regresja